on: issues

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Add markdown
        run: |
          cd ./_markdowns
          cat <<EOF > ${{ github.event.issue.title }}.md
          ${{ github.event.issue.body }}
          EOF
          ls .
          cat ${{ github.event.issue.title }}.md
